runtime: java
env: flex
runtime_config:
  jdk: openjdk8
service: default

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
- url: /.*
  script: this field is required, but ignored
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.5
network: {}
       
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  